[build]
builder = "nixpacks"
buildCommand = "cd client && npm install && npm run build && cd ../server && npm install && npx prisma generate"

[deploy]
startCommand = "cd server && npx prisma db push --accept-data-loss && node index.js"
healthcheckPath = "/api/categories"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
