[build]
builder = "nixpacks"
buildCommand = "cd client && npm install && npm run build && cd ../server && npm install && npx prisma generate"

[deploy]
startCommand = "cd server && npx prisma db push && node index.js"
healthcheckPath = "/api/categories"
restartPolicyType = "on_failure"
